In [1]:
import numpy as np

a = np.random.randint(1,100,15)   # 1D
b = np.random.randint(1,100,24).reshape(6,4)     # 2D

In [2]:
a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [3]:
b

array([[60, 80,  5, 11],
       [ 1, 23, 46, 61],
       [42, 73, 38, 11],
       [41, 74, 74, 13],
       [54, 36, 88, 19],
       [ 4, 65,  5, 45]], dtype=int32)

In [4]:
# 1> np.sort   # To sort array in acending or descending order and in 2D array sort array rows wise and column wise

np.sort(a)

array([ 2,  7, 15, 30, 31, 33, 36, 48, 49, 54, 54, 62, 69, 72, 89],
      dtype=int32)

In [5]:
np.sort(b)

array([[ 5, 11, 60, 80],
       [ 1, 23, 46, 61],
       [11, 38, 42, 73],
       [13, 41, 74, 74],
       [19, 36, 54, 88],
       [ 4,  5, 45, 65]], dtype=int32)

In [6]:
np.sort(b,axis=0)

array([[ 1, 23,  5, 11],
       [ 4, 36,  5, 11],
       [41, 65, 38, 13],
       [42, 73, 46, 19],
       [54, 74, 74, 45],
       [60, 80, 88, 61]], dtype=int32)

In [7]:
np.sort(a)[::-1]

array([89, 72, 69, 62, 54, 54, 49, 48, 36, 33, 31, 30, 15,  7,  2],
      dtype=int32)

In [8]:
# 2> np.append   # to add anything in array

np.append(a,200)  #1D


array([ 31,   2,  48,  15,  89,  33,  54,  36,  62,  49,  54,  30,  69,
         7,  72, 200])

In [11]:
np.append(b,ones((b.shape[0],1)),axis=0)

NameError: name 'ones' is not defined

In [12]:
# 3> np.concatenate  # add two or more array, row and column wise 

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)

[[0 1 2]
 [3 4 5]]


In [13]:
print(d)

[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)  # column wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)  # row wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [16]:
# 4> np.unique   # To find unique value in array means same value in array or value have in array in multiple time

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9])
np.unique(e)   # repeted value in array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# 5> np.expand_dims   # converting array  1D into 2D, 2D into 3D, 3D into 4D and so on......

a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [18]:
a.shape

(15,)

In [19]:
np.expand_dims(a,axis=0).shape   # column

(1, 15)

In [20]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [21]:
# 6> np.where   # np.where(condition,True,False)

a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [22]:
np.where(a > 50)

(array([ 4,  6,  8, 10, 12, 14]),)

In [23]:
np.where(a > 50 , 0 , a)   # replace all value > 50 with 0

array([31,  2, 48, 15,  0, 33,  0, 36,  0, 49,  0, 30,  0,  7,  0],
      dtype=int32)

In [24]:
np.where(a % 2 == 0 ,0,a)   # replace even number by 0

array([31,  0,  0, 15, 89, 33,  0,  0,  0, 49,  0,  0, 69,  7,  0],
      dtype=int32)

In [25]:
# 7> np.argmax   # It will shows max value in array

a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [26]:
np.argmax(a)   # 1D

np.int64(4)

In [27]:
b

array([[60, 80,  5, 11],
       [ 1, 23, 46, 61],
       [42, 73, 38, 11],
       [41, 74, 74, 13],
       [54, 36, 88, 19],
       [ 4, 65,  5, 45]], dtype=int32)

In [28]:
np.argmax(b,axis=0)   # column wise max value

array([0, 0, 4, 1])

In [29]:
np.argmax(b,axis=1)   # rows wise max value

array([1, 3, 1, 1, 2, 1])

In [30]:
np.argmin(a)

np.int64(1)

In [31]:
np.argmin(b,axis=0)

array([1, 1, 0, 0])

In [32]:
np.argmin(b,axis=1)

array([2, 0, 3, 3, 3, 0])

In [33]:
# # Stactic Function

# 8> np.cumsum

# sum of whole array

a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [34]:
np.cumsum(a)

array([ 31,  33,  81,  96, 185, 218, 272, 308, 370, 419, 473, 503, 572,
       579, 651])

In [35]:
b

array([[60, 80,  5, 11],
       [ 1, 23, 46, 61],
       [42, 73, 38, 11],
       [41, 74, 74, 13],
       [54, 36, 88, 19],
       [ 4, 65,  5, 45]], dtype=int32)

In [36]:
np.cumsum(b,axis=0)   # column

array([[ 60,  80,   5,  11],
       [ 61, 103,  51,  72],
       [103, 176,  89,  83],
       [144, 250, 163,  96],
       [198, 286, 251, 115],
       [202, 351, 256, 160]])

In [37]:
np.cumsum(b,axis=1)  # rows

array([[ 60, 140, 145, 156],
       [  1,  24,  70, 131],
       [ 42, 115, 153, 164],
       [ 41, 115, 189, 202],
       [ 54,  90, 178, 197],
       [  4,  69,  74, 119]])

In [38]:
# 9> np.cumprod  # multiple all array

np.cumprod(a)

array([                  31,                   62,                 2976,
                      44640,              3972960,            131107680,
                 7079814720,         254873329920,       15802146455040,
            774305176296960,    41812479520035840,  1254374385601075200,
       -5681887762073569280, -2879726187095881728, -4426100660098416640])

In [39]:
np.cumprod(b,axis=0)

array([[         60,          80,           5,          11],
       [         60,        1840,         230,         671],
       [       2520,      134320,        8740,        7381],
       [     103320,     9939680,      646760,       95953],
       [    5579280,   357828480,    56914880,     1823107],
       [   22317120, 23258851200,   284574400,    82039815]])

In [40]:
np.cumprod(b,axis=1)

array([[     60,    4800,   24000,  264000],
       [      1,      23,    1058,   64538],
       [     42,    3066,  116508, 1281588],
       [     41,    3034,  224516, 2918708],
       [     54,    1944,  171072, 3250368],
       [      4,     260,    1300,   58500]])

In [41]:
# 10> np.percentile

a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [42]:
np.percentile(a,100)

np.float64(89.0)

In [43]:
np.percentile(a,50)

np.float64(48.0)

In [44]:
np.percentile(a,0)

np.float64(2.0)

In [45]:
np.median(a)

np.float64(48.0)

In [46]:
# 11> np.histogram   # count frequency bins wise

a

array([31,  2, 48, 15, 89, 33, 54, 36, 62, 49, 54, 30, 69,  7, 72],
      dtype=int32)

In [47]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 0, 4, 2, 2, 2, 1, 1, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [48]:
# 12> np.corrcoef  # correlation and coefficient

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [51]:
# 13> np.isin   # To check the value are present in array or not, using different array.

a = np.random.randint(1,100,15)
items = [10,20,30,40,50,60,70,80,90,100]

a

array([ 8, 95, 49, 59, 67, 96, 59, 26, 41, 20, 99, 74, 61, 88, 42],
      dtype=int32)

In [52]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)   # it will shows boolean array

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False])

In [50]:
a[np.isin(a,items)]    # exact number

array([80, 30, 40, 50], dtype=int32)

In [53]:
# 14> np.flip  # It will shows mirror array as revers

a

array([ 8, 95, 49, 59, 67, 96, 59, 26, 41, 20, 99, 74, 61, 88, 42],
      dtype=int32)

In [54]:
np.flip(a)

array([42, 88, 61, 74, 99, 20, 41, 26, 59, 96, 67, 59, 49, 95,  8],
      dtype=int32)

In [55]:
b

array([[60, 80,  5, 11],
       [ 1, 23, 46, 61],
       [42, 73, 38, 11],
       [41, 74, 74, 13],
       [54, 36, 88, 19],
       [ 4, 65,  5, 45]], dtype=int32)

In [56]:
np.flip(b)

array([[45,  5, 65,  4],
       [19, 88, 36, 54],
       [13, 74, 74, 41],
       [11, 38, 73, 42],
       [61, 46, 23,  1],
       [11,  5, 80, 60]], dtype=int32)

In [57]:
# 15> np.put  # It will replace specific element when user give index and what to replace then it will worke
# np.put(parameter , index, what to replace)
a

array([ 8, 95, 49, 59, 67, 96, 59, 26, 41, 20, 99, 74, 61, 88, 42],
      dtype=int32)

In [58]:
np.put(a,[0,1],[111,222])

In [59]:
a

array([111, 222,  49,  59,  67,  96,  59,  26,  41,  20,  99,  74,  61,
        88,  42], dtype=int32)

In [61]:
np.put(a,[6,4],[99,88])
a

array([111, 222,  49,  59,  88,  96,  99,  26,  41,  20,  99,  74,  61,
        88,  42], dtype=int32)

In [62]:
b

array([[60, 80,  5, 11],
       [ 1, 23, 46, 61],
       [42, 73, 38, 11],
       [41, 74, 74, 13],
       [54, 36, 88, 19],
       [ 4, 65,  5, 45]], dtype=int32)

In [63]:
np.put(b,[2,2],[99])
b       

array([[60, 80, 99, 11],
       [ 1, 23, 46, 61],
       [42, 73, 38, 11],
       [41, 74, 74, 13],
       [54, 36, 88, 19],
       [ 4, 65,  5, 45]], dtype=int32)

In [64]:
# 16> np.delete 

a = np.random.randint(1,100,15)
a

array([94, 78, 68, 74, 36, 72,  9, 26,  4, 99, 87, 62, 76, 26, 70],
      dtype=int32)

In [65]:
np.delete(a,[0,2,5])

array([78, 74, 36,  9, 26,  4, 99, 87, 62, 76, 26, 70], dtype=int32)

In [66]:
## 17> Set Function


m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [67]:
# 1> np.union1d

np.union1d(m,n)   # all value present in both array

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
# 2> np.intersect1d

np.intersect1d(m,n)   # The value which are comman in both array

array([3, 4, 5])

In [69]:
# 3> np.setdiff1d

np.setdiff1d(m,n) # the value not present in n but present in m

array([1, 2])

In [70]:
np.setdiff1d(n,m)

array([6, 7])

In [71]:
# 4> np.setxor1d

np.setxor1d(m,n)  # Not comman in both array

array([1, 2, 6, 7])

In [72]:
# 5> np.in1d

np.in1d(m,1)

C:\Users\heman\AppData\Local\Temp\ipykernel_16516\3541711508.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [73]:
np.in1d(m,10)

C:\Users\heman\AppData\Local\Temp\ipykernel_16516\3337556509.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,10)


array([False, False, False, False, False])

In [74]:
np.in1d(n,6)

C:\Users\heman\AppData\Local\Temp\ipykernel_16516\2184744311.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(n,6)


array([False, False, False,  True, False])

In [75]:
# 18> np.clip  # using clip we can fix min value and max value of array

a = np.random.randint(1,100,15)
a

array([76, 32,  8,  7, 17, 89, 42, 41, 96, 95, 19, 95, 37, 84, 50],
      dtype=int32)

In [ ]:
np.clip(a,