In [1]:
# 1> creating nd array
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3D array

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# D-type

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [10]:
# 2> arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# 3> with reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# 4> ones and zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# 5> random

np.random.random((3,4))

array([[0.67864907, 0.00935289, 0.16881234, 0.28113546],
       [0.74079349, 0.19727635, 0.33359484, 0.82263697],
       [0.01739407, 0.01213316, 0.25475852, 0.87719333]])

In [22]:
# 6> linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
# 7> identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
## Numpy Attributes OR Array Attributes

a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [5]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [6]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
# 1> ndim

a1.ndim   # dimension of given array

1

In [28]:
# 2> shape

a1.shape  # how many row and column are in matrics

(10,)

In [30]:
a2.shape

(3, 4)

In [31]:
a3.shape

(2, 2, 2)

In [32]:
# 3> Size

a3.size    # No. of Item in the matrics

8

In [33]:
a2.size

12

In [34]:
a1.size

10

In [35]:
# 4> Itemsize

a3.itemsize    # memory occupied by item 

8

In [36]:
a2.itemsize

8

In [39]:
a1.itemsize

4

In [40]:
# 5> d-type

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)  # Data Type of numpy or function

int32
float64
int64


In [7]:
# changing datatype

# astype
a3.astype(np.int32)
print(a3.dtype)

int64


In [18]:
### Array Operation

a1 = np.array(12).reshape(3,4)
a2 = np.array(12,24).reshape(3,4)
a1

ValueError: cannot reshape array of size 1 into shape (3,4)

In [9]:
## 1> Scalaer operation
# a> Arithmetic

a1 * 2    ## were every item is multiply by 2 of matrics

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int32)

In [10]:
a1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [11]:
a1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
a1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [13]:
# b> Relational

a2 > 5   # comapre every item of matrics

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
a2  == 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
## 2> Vector Operation

# arithmetic

a1 + a2

In [17]:
a1 * a2

ValueError: operands could not be broadcast together with shapes (10,) (3,4) 

In [31]:
# ARRAY FUNCTION

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[31., 17., 13.],
       [21., 10., 90.],
       [86., 47.,  7.]])

In [32]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [20]:
# 1> Max / Min / Sum / Prod

np.max(a1)   # maxmium number in the matrics

np.float64(96.0)

In [21]:
np.min(a1)

np.float64(1.0)

In [22]:
np.sum(a1)

np.float64(400.0)

In [23]:
np.prod(a1)

np.float64(5747750461440.0)

In [25]:
np.max(a1,axis=1)     # rows wise  =1


array([52., 96., 72.])

In [26]:
np.max(a1,axis=0)    # column wise  =0



array([72., 96., 67.])

In [27]:
np.min(a1,axis=1)


array([17.,  9.,  1.])

In [28]:
np.prod(a1,axis=0)

array([16848., 97920.,  3484.])

In [29]:
np.min(a1,axis=0)

array([ 9., 17.,  1.])

In [30]:
np.sum(a1,axis=0)

array([107., 173., 120.])

In [33]:
# 2> Mean / Median / Std / Var

np.mean(a1)

np.float64(35.77777777777778)

In [34]:
np.mean(a1,axis=1)

array([20.33333333, 40.33333333, 46.66666667])

In [35]:
np.mean(a1,axis=0)

array([46.        , 24.66666667, 36.66666667])

In [36]:
## Dot Product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [37]:
# 1> Log and Exponents

np.log(a1)

array([[3.4339872 , 2.83321334, 2.56494936],
       [3.04452244, 2.30258509, 4.49980967],
       [4.4543473 , 3.8501476 , 1.94591015]])

In [38]:
np.exp(a1)

array([[2.90488497e+13, 2.41549528e+07, 4.42413392e+05],
       [1.31881573e+09, 2.20264658e+04, 1.22040329e+39],
       [2.23524660e+37, 2.58131289e+20, 1.09663316e+03]])

In [39]:
# 2> Round / Floor / Ceil

np.round(np.random.random((2,3))*100)

array([[96., 73., 38.],
       [82., 40.,  8.]])

In [40]:
np.floor(np.random.random((2,3))*100)

array([[25., 20., 88.],
       [77., 47., 34.]])

In [41]:
np.ceil(np.random.random((2,3))*100)

array([[67., 11., 46.],
       [73., 20., 52.]])

In [5]:
## Indexing and Slicing

a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
# 1> Indexing  # 1D

a1[0]

np.int64(0)

In [47]:
a1[-1]

np.int64(9)

In [48]:
a1[5]

np.int64(5)

In [49]:
# 2D  Indexing

a2[1,2]

np.int64(6)

In [50]:
a2[2,3]

np.int64(11)

In [58]:
# 3D Indexing

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
a3[1,0,1]

np.int64(5)

In [60]:
a3[0,0,0]

np.int64(0)

In [11]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 2> Slicing

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a2 [1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [17]:
a2 [::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [18]:
a2 [::2,1::3]

array([[1],
       [9]])

In [19]:
a3 [0::2]

array([[[0, 1],
        [2, 3]]])

In [22]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
a3 [2,1:,1:]

array([[22, 23],
       [25, 26]])

In [24]:
a3 [::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [25]:
# Iterating

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [29]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [30]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [31]:
# 3D


for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [32]:
# Reshaping :-
              # 1> reshape
              # 2> Transpose
              # 3> Ravel

# 2> Transpose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [33]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [34]:
# 3> Ravel

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [39]:
## Stacking

a4 = np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
# 1> Horizontal Stacking
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [45]:
# 2> Vertical Stacking

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
## Splitting

# 1> Horizontal Splitting

a4

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [47]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [48]:
# 2> Vertical Splitting

np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]