In [1]:
import numpy as np

In [2]:
# 1> creating numpy / n-d array

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 3> Zeros

arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# 4> Ones

arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr7 = np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
arr8 = np.arange(5,16,2)
arr8

array([ 5,  7,  9, 11, 13, 15])

In [11]:
arr9 = np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
arr10 = arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [13]:
arr1.shape

(5,)

In [14]:
arr2.shape

(2, 3)

In [15]:
arr11 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr11

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
arr11.shape

(2, 2, 2)

In [17]:
arr11.ndim

3

In [18]:
arr2.ndim

2

In [19]:
arr1.ndim

1

In [20]:
## size

arr1.size

5

In [21]:
arr11.size

8

In [22]:
arr11.itemsize

8

In [23]:
arr9.itemsize

8

In [24]:
arr9.dtype

dtype('float64')

In [25]:
arr11.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [28]:
arr11.astype('int32')

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [29]:
## List vS Array

lista = range(100)
arr12 = np.arange(100)

In [30]:
import sys

In [32]:
print(sys.getsizeof(87)*len(lista))

2800


In [34]:
print(arr12.itemsize*arr12.size)

800


In [35]:
import time

In [36]:
# list
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()

c = [(x + y) for x,y in zip(x,y)]

print(time.time() - start_time)

2.132155656814575


In [37]:
# numpy
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start_time = time.time()

c = a + b

print(time.time() - start_time)

0.24985861778259277


In [39]:
arr13 = np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
arr1

array([1, 2, 3, 4, 5])

In [41]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
arr13[2]

array([ 8,  9, 10, 11])

In [44]:
arr13[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [45]:
arr13[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [48]:
arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [50]:
arr13[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [51]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
for i in arr13:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [53]:
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [54]:
## Numpy basic operation

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [55]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [56]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [57]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])