In [1]:
import numpy as np

dt = np.dtype([('age',np.int8)])

a = np.array([(10,),(20,),(30,)],dtype = dt)

print(a['age'])

[10 20 30]


In [2]:
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [3]:
np.eye(a)

TypeError: only integer scalar arrays can be converted to a scalar index

In [10]:
b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
np.eye(b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [12]:
import numpy as np
a = np.array([7 ,10 ,2 ,4 ,13 , 16])

med = np.percentile(a, 50)
print(med)

8.5


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[